<?php

namespace Database\Factories\Purchase;

use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\Master\Store;
use App\Models\Master\Supplier;
use App\Models\Master\Warehouse;

class PurchaseFactory extends Factory
{
    protected $model = \App\Models\Purchase\Purchase::class;

    public function definition(): array
    {
        return [
            'store_id' => Store::inRandomOrder()->first()->id ?? Store::factory(),
            'supplier_id' => Supplier::inRandomOrder()->first()->id ?? Supplier::factory(),
            'warehouse_id' => Warehouse::inRandomOrder()->first()->id ?? Warehouse::factory(),
            'created_by' => 1,
            'reference_no' => 'PI-202605-' . str_pad($this->faker->unique()->numberBetween(1, 9999), 4, '0', STR_PAD_LEFT),
            'type' => 'purchase',
            'status' => 'received',
            'payment_status' => 'paid',
            'total_items' => 0,
            'total_amount' => 0,
            'tax_amount' => 0,
            'discount_amount' => 0,
            'shipping_cost' => 0,
            'grand_total' => 0,
            'notes' => 'Generated by factory',
        ];
    }
}
